# Generated by Django 5.0.4 on 2024-05-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlacklistedTokens',
            new_name='BlacklistedToken',
        ),
    ]
