# Generated by Django 5.0.4 on 2024-05-12 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersfollows_follower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersFollows',
            new_name='UserFollow',
        ),
        migrations.RenameModel(
            old_name='UsersProfiles',
            new_name='UserProfile',
        ),
    ]
