# Generated by Django 5.0.4 on 2024-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userfollow_follower_alter_userfollow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
